spring.application.name=expensetracker

spring.datasource.url = ${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

server.port=${SERVER_PORT:8080}

spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql = true
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

jwt.secret=${JWT_SECRET:s3cR3tK3y!@#4567890qwertyuiopasdfgh}
jwt.expiration=${JWT_EXPIRATION:3600000}

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always


baseUrl=pjsofttech